version: '3'

services:
    master:
      build: ./
      container_name: redis_server
      
      ports:
         - "6379:6379"
      expose: 
        - "6379"
      volumes:
         # 数据持久化
         - ./data:/data
      command: redis-server /usr/local/etc/redis/redis.conf